import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/header';
import localFont from 'next/font/local';

const nexaLight = localFont({
  src: '../fonts/Nexa/Nexa-ExtraLight.ttf',
  variable: '--font-nexa-light',
});

const nexaBold = localFont({
  src: '../fonts/Nexa/Nexa-Heavy.ttf',
  variable: '--font-nexa-bold',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
      </head>
      <body>
        <Header />
        <main className={`${nexaLight.variable} ${nexaBold.variable}`}>
          {children}
        </main>
      </body>
    </html>
  );
}
